name: CI

on:
  repository_dispatch:
    type: [build]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      BUILD_ENGINE: postgresql://postgres@localhost:5436/postgres
      EDM_DATA: ${{ secrets.EDM_DATA }}
    steps:
      - uses: actions/checkout@v2
      - run: sh 01_dataloading.sh
      - run: sh 02_geocoding.sh
      - run: sh 03_build.sh
      - run: sh 04_export.sh
